"""add user project configs and extend user sessions

Revision ID: 5b6ee90a9767
Revises: 8d6e2b7af5d7
Create Date: 2026-01-13 09:49:11.518922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b6ee90a9767'
down_revision: Union[str, Sequence[str], None] = '8d6e2b7af5d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_project_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bot_key', sa.String(length=100), nullable=False, comment='所属 Bot Key'),
    sa.Column('chat_id', sa.String(length=200), nullable=False, comment='用户/群 ID'),
    sa.Column('project_id', sa.String(length=100), nullable=False, comment="项目标识（如 'test', 'prod'）"),
    sa.Column('project_name', sa.String(length=200), nullable=True, comment='项目名称（显示用）'),
    sa.Column('url_template', sa.Text(), nullable=False, comment='转发目标 URL 模板'),
    sa.Column('agent_id', sa.String(length=100), nullable=True, comment='Agent ID (历史字段，保留用于兼容)'),
    sa.Column('api_key', sa.String(length=200), nullable=True, comment='转发请求的 API Key'),
    sa.Column('timeout', sa.Integer(), nullable=False, comment='转发请求超时时间 (秒)'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='是否为该用户的默认项目'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_key', 'chat_id', 'project_id', name='uq_user_project_bot_chat_project')
    )
    with op.batch_alter_table('user_project_configs', schema=None) as batch_op:
        batch_op.create_index('idx_user_projects_default', ['bot_key', 'chat_id', 'is_default'], unique=False)
        batch_op.create_index('idx_user_projects_lookup', ['bot_key', 'chat_id', 'enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_project_configs_bot_key'), ['bot_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_project_configs_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_project_configs_enabled'), ['enabled'], unique=False)

    with op.batch_alter_table('forward_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.String(length=100), nullable=True, comment='使用的项目 ID'))
        batch_op.add_column(sa.Column('project_name', sa.String(length=200), nullable=True, comment='项目名称（用于显示）'))
        batch_op.create_index(batch_op.f('ix_forward_logs_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_project_id', sa.String(length=100), nullable=True, comment='当前使用的项目 ID'))
        batch_op.add_column(sa.Column('project_config_id', sa.Integer(), nullable=True, comment='关联的项目配置 ID (外键)'))
        batch_op.create_index('idx_user_session_project', ['current_project_id'], unique=False)
        batch_op.create_foreign_key('fk_user_sessions_project_config', 'user_project_configs', ['project_config_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_sessions_project_config', type_='foreignkey')
        batch_op.drop_index('idx_user_session_project')
        batch_op.drop_column('project_config_id')
        batch_op.drop_column('current_project_id')

    with op.batch_alter_table('forward_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forward_logs_project_id'))
        batch_op.drop_column('project_name')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('user_project_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_project_configs_enabled'))
        batch_op.drop_index(batch_op.f('ix_user_project_configs_chat_id'))
        batch_op.drop_index(batch_op.f('ix_user_project_configs_bot_key'))
        batch_op.drop_index('idx_user_projects_lookup')
        batch_op.drop_index('idx_user_projects_default')

    op.drop_table('user_project_configs')
    # ### end Alembic commands ###
