"""init: 创建初始数据库表结构

Revision ID: 8d6e2b7af5d7
Revises: 
Create Date: 2026-01-11 20:40:02.085257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d6e2b7af5d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bot_key', sa.String(length=100), nullable=False, comment='企微机器人 Webhook Key (唯一)'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Bot 名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='Bot 描述'),
    sa.Column('url_template', sa.String(length=500), nullable=False, comment='转发目标 URL 模板 (支持 {agent_id} 占位符)'),
    sa.Column('agent_id', sa.String(length=100), nullable=True, comment='Agent ID (用于 URL 模板替换)'),
    sa.Column('api_key', sa.String(length=200), nullable=True, comment='转发请求的 API Key (可选)'),
    sa.Column('timeout', sa.Integer(), nullable=False, comment='转发请求超时时间 (秒)'),
    sa.Column('access_mode', sa.String(length=20), nullable=False, comment='访问控制模式: allow_all, whitelist, blacklist'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chatbots', schema=None) as batch_op:
        batch_op.create_index('idx_chatbots_bot_key', ['bot_key'], unique=False)
        batch_op.create_index('idx_chatbots_enabled', ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatbots_bot_key'), ['bot_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_chatbots_enabled'), ['enabled'], unique=False)

    op.create_table('forward_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='请求时间'),
    sa.Column('chat_id', sa.String(length=200), nullable=False, comment='群聊/会话 ID'),
    sa.Column('from_user_id', sa.String(length=100), nullable=False, comment='发送者用户 ID'),
    sa.Column('from_user_name', sa.String(length=100), nullable=True, comment='发送者用户名'),
    sa.Column('content', sa.Text(), nullable=False, comment='用户发送的消息内容'),
    sa.Column('msg_type', sa.String(length=20), nullable=False, comment='消息类型 (text/image/mixed)'),
    sa.Column('bot_key', sa.String(length=100), nullable=True, comment='使用的 Bot Key'),
    sa.Column('bot_name', sa.String(length=100), nullable=True, comment='Bot 名称'),
    sa.Column('target_url', sa.Text(), nullable=False, comment='转发的目标 URL'),
    sa.Column('session_id', sa.String(length=100), nullable=True, comment='Agent 会话 ID'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: pending/success/error/timeout'),
    sa.Column('response', sa.Text(), nullable=True, comment='Agent 响应内容'),
    sa.Column('error', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('duration_ms', sa.Integer(), nullable=False, comment='请求耗时（毫秒）'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forward_logs', schema=None) as batch_op:
        batch_op.create_index('idx_forward_logs_bot_key', ['bot_key'], unique=False)
        batch_op.create_index('idx_forward_logs_chat_id', ['chat_id'], unique=False)
        batch_op.create_index('idx_forward_logs_status', ['status'], unique=False)
        batch_op.create_index('idx_forward_logs_timestamp', ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_forward_logs_bot_key'), ['bot_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_forward_logs_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forward_logs_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forward_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('processing_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_key', sa.String(length=500), nullable=False, comment='会话唯一标识: user_id:chat_id:bot_key'),
    sa.Column('user_id', sa.String(length=100), nullable=False, comment='用户 ID'),
    sa.Column('chat_id', sa.String(length=200), nullable=False, comment='Chat ID'),
    sa.Column('bot_key', sa.String(length=100), nullable=False, comment='Bot Key'),
    sa.Column('message', sa.String(length=500), nullable=False, comment='正在处理的消息内容 (截断)'),
    sa.Column('started_at', sa.DateTime(), nullable=False, comment='处理开始时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processing_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processing_sessions_session_key'), ['session_key'], unique=True)

    op.create_table('system_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False, comment='配置键'),
    sa.Column('value', sa.Text(), nullable=False, comment='配置值 (JSON 格式)'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='配置描述'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_config_key'), ['key'], unique=True)

    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False, comment='用户 ID'),
    sa.Column('chat_id', sa.String(length=200), nullable=False, comment='Chat ID (群ID或私聊ID)'),
    sa.Column('bot_key', sa.String(length=100), nullable=False, comment='关联的 Bot Key'),
    sa.Column('session_id', sa.String(length=100), nullable=False, comment='Agent 返回的 Session ID'),
    sa.Column('short_id', sa.String(length=8), nullable=False, comment='Session ID 短标识 (前8位)'),
    sa.Column('last_message', sa.String(length=500), nullable=True, comment='用户最后一条消息 (用于展示)'),
    sa.Column('message_count', sa.Integer(), nullable=False, comment='消息计数'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否为当前活跃会话'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_user_session_active', ['user_id', 'chat_id', 'bot_key', 'is_active'], unique=False)
        batch_op.create_index('idx_user_session_short_id', ['user_id', 'chat_id', 'short_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_bot_key'), ['bot_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_short_id'), ['short_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('chat_access_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chatbot_id', sa.Integer(), nullable=False, comment='关联的 Bot ID'),
    sa.Column('chat_id', sa.String(length=200), nullable=False, comment='Chat ID (用户ID或群ID)'),
    sa.Column('rule_type', sa.String(length=20), nullable=False, comment='规则类型: whitelist 或 blacklist'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注说明'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chatbot_id', 'chat_id', 'rule_type', name='uq_chatbot_chat_rule')
    )
    with op.batch_alter_table('chat_access_rules', schema=None) as batch_op:
        batch_op.create_index('idx_access_rules_chat_id', ['chat_id'], unique=False)
        batch_op.create_index('idx_access_rules_chatbot_id', ['chatbot_id'], unique=False)
        batch_op.create_index('idx_access_rules_rule_type', ['rule_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_access_rules_chatbot_id'), ['chatbot_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_access_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_access_rules_chatbot_id'))
        batch_op.drop_index('idx_access_rules_rule_type')
        batch_op.drop_index('idx_access_rules_chatbot_id')
        batch_op.drop_index('idx_access_rules_chat_id')

    op.drop_table('chat_access_rules')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_short_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_session_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_is_active'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_chat_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_bot_key'))
        batch_op.drop_index('idx_user_session_short_id')
        batch_op.drop_index('idx_user_session_active')

    op.drop_table('user_sessions')
    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_config_key'))

    op.drop_table('system_config')
    with op.batch_alter_table('processing_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processing_sessions_session_key'))

    op.drop_table('processing_sessions')
    with op.batch_alter_table('forward_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forward_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_forward_logs_session_id'))
        batch_op.drop_index(batch_op.f('ix_forward_logs_chat_id'))
        batch_op.drop_index(batch_op.f('ix_forward_logs_bot_key'))
        batch_op.drop_index('idx_forward_logs_timestamp')
        batch_op.drop_index('idx_forward_logs_status')
        batch_op.drop_index('idx_forward_logs_chat_id')
        batch_op.drop_index('idx_forward_logs_bot_key')

    op.drop_table('forward_logs')
    with op.batch_alter_table('chatbots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chatbots_enabled'))
        batch_op.drop_index(batch_op.f('ix_chatbots_bot_key'))
        batch_op.drop_index('idx_chatbots_enabled')
        batch_op.drop_index('idx_chatbots_bot_key')

    op.drop_table('chatbots')
    # ### end Alembic commands ###
