"""init: 创建初始数据库表结构

Revision ID: a79faa4d7c04
Revises: 
Create Date: 2026-01-11 21:26:10.070249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a79faa4d7c04'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hil_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('short_id', sa.String(length=8), nullable=False),
    sa.Column('chat_id', sa.String(length=255), nullable=False),
    sa.Column('chat_type', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expire_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hil_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_chat_status', ['chat_id', 'status'], unique=False)
        batch_op.create_index('idx_expire_status', ['expire_at', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_hil_sessions_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hil_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_hil_sessions_session_id'), ['session_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_hil_sessions_short_id'), ['short_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hil_sessions_status'), ['status'], unique=False)

    op.create_table('hil_replies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('msg_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('from_user', sa.JSON(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['hil_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hil_replies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hil_replies_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hil_replies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hil_replies_session_id'))

    op.drop_table('hil_replies')
    with op.batch_alter_table('hil_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hil_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_hil_sessions_short_id'))
        batch_op.drop_index(batch_op.f('ix_hil_sessions_session_id'))
        batch_op.drop_index(batch_op.f('ix_hil_sessions_created_at'))
        batch_op.drop_index(batch_op.f('ix_hil_sessions_chat_id'))
        batch_op.drop_index('idx_expire_status')
        batch_op.drop_index('idx_chat_status')

    op.drop_table('hil_sessions')
    # ### end Alembic commands ###
