#!/bin/bash
# HIL Server 启动脚本示例

echo "=== HIL Server 启动示例 ==="
echo ""
echo "使用方式:"
echo ""
echo "1. Direct 模式(内网部署,直接调用 fly-pigeon):"
echo "   cd packages/hil-server"
echo "   export BOT_KEY='your_bot_key'"
echo "   export HIL_PORT=8081"
echo "   uv run python -m hil_server.app"
echo ""
echo "2. Relay 模式(公网部署,需要 Worker 连接):"
echo "   cd packages/hil-server"
echo "   export HIL_PORT=8081"
echo "   export HIL_WORKER_TOKEN='your_token'"
echo "   uv run python -m hil_server.app"
echo ""
echo "3. 使用数据库模式:"
echo "   USE_DATABASE=true \\"
echo "   DATABASE_URL='sqlite:///./data/hil.db' \\"
echo "   uv run python -m hil_server.app"
echo ""
echo "=== 配置说明 ==="
echo "- BOT_KEY:         fly-pigeon 的 bot key (Direct 模式必需)"
echo "- HIL_PORT:        服务端口 (默认 8081)"
echo "- HIL_WORKER_TOKEN: Worker 认证令牌 (Relay 模式)"
echo "- USE_DATABASE:    是否使用数据库 (true/false)"
echo "- DATABASE_URL:    数据库连接字符串"
echo ""
